# Generated by Django 4.1 on 2022-09-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'ordering': ['tag__label']},
        ),
    ]
